<?php 
$id = $this->getRequest()->getParam('id');
$status = $this->getConfig('booksettings/general/enable');
$height = $this->getConfig('booksettings/general/display_height');
$width = $this->getConfig('booksettings/general/display_width');
$duration = $this->getConfig('booksettings/general/display_duration');
$book = $this->getBook($id); 
?>
<?php if($id): ?>

	<div class="flipbook-viewport">
		<div class="container">
			<div class="flipbook" id="container1">
				<?php $files = $this->getBookPages($book); ?>
				<?php foreach ($files as $file) { ?>
					<div style="<?php echo $this->getbackgroundImage($book, $file); ?>"></div>
				<?php }  ?>
			</div>
		</div>
	</div>
	<script type="text/javascript">

		require(["jquery","html2canvas","three","pdf","flipbook"], function($, html2canvas, three){
			'use strict'
			// console.log(EventDispatcher);
			var EventDispatcher = window.EventDispatcher = window.EventDispatcher || {};
			console.log(html2canvas);
			console.log(three);
			console.log(window.EventDispatcher);
			var EventDispatcher = window.EventDispatcher;
	      	$('#container1').FlipBook({
	      		pdf: ['<?php echo $this->getBookPath($book->getUpload()); ?>'],
	      		template: {
					html:['<?php echo $this->getViewFileUrl('Book_Flip::template/default-book-view.html'); ?>'],
					links: [{
						rel: 'stylesheet',
						href: ['<?php echo $this->getViewFileUrl('Book_Flip::css/font-awesome.min.css'); ?>']
					}],
					styles: ['<?php echo $this->getViewFileUrl('Book_Flip::css/short-black-book-view.css'); ?>'],
					script: ['<?php echo $this->getViewFileUrl('Book_Flip::js/plugin/default-book-view.js'); ?>']
				}
	      	});
		});

	</script>

	<div class="book-details">
		<div class="book-title"><?php echo $book->getTitle(); ?></div>
	</div>
<?php endif; ?>
